name: inputs-demo
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug


jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        run: |
          echo "Log level: ${{ inputs.logLevel }}"
     
