name: inputs-demo
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Loglevel'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      tags:
        description: "test"
        required: false
        type: boolean


jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs
        run: |
          echo "Log level: ${{ inputs.logLevel }}"
     
