name: environments
on: [push]
env:
  project: "roboshop"
  component: "catalogue"

jobs:
  github-env:
    runs-on: ubuntu-latest
    steps:
      - name: print env
        run: |
          echo "project: $project"
          echo "component: $component"
      - name: print secrets
        run: |
          echo " DB_USER: ${{ secrets.DB_USER }}"
          echo "DB_PASSWORD:  ${{ secrets.DB_PASSWORD }}"

      - name: print vars 
        run: |
          echo "DB_URL: ${{ vars.DB_URL }}"
    