name: environments
on: [push]
env:
  project: "roboshop"
  component: "catalogue"

jobs:
  github-env:
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.step1.outputs.image_name }}
      image_version: ${{ steps.step1.outputs.image_version}}
    steps:
      - name: print env
        run: |
          echo "project: $project"
          echo "component: $component"
      - name: print secrets
        run: |
          echo " DB_USER: ${{ secrets.DB_USER }}"
          echo "DB_PASSWORD:  ${{ secrets.DB_PASSWORD }}"

      - name: print vars 
        run: |
          echo "DB_URL: ${{ vars.DB_URL }}"

      - name: image and version
        id: step1
        run: |
          echo "image_name=nginx" >> $GITHUB_OUTPUT
          echo "image_version=1.0.0" >> $GITHUB_OUTPUT
        
      - name: print outputs
        run: | 
          echo "image_name: ${{ steps.step1.outputs.image_name }}"
          echo "image_version: ${{ steps.step1.outputs.image_version }}"

      # using within job 
      - name: using githubenv
        run: |
          echo "course=devops" >> $GITHUB_ENV
          echo "duration=2hrs" >> $GITHUB_ENV
        
      - name: access using GITHUB_ENV
        run: |
          echo "course: $course"
          echo "duration: $duration"

  deploy:
    needs: github-env
    runs-on: ubuntu-latest
    steps:
      - name:  print github env in another job
        run: |
          echo "image_name: ${{ needs.githubenv.image_name }}"
          echo "image_name: ${{ needs.githubenv.image_version }}"


