name: workflowcall-pipeline
on: [push]

jobs:
  feature-pipeline:
    uses: devopsactios/workflows/.github/workflows/nodejs-feature-pipeline.yaml@main
    with:
      project: 'roboshop'
      components: 'catalogue'
      environment: 'dev' 
    
